import test from 'node:test';
import assert from 'node:assert/strict';
import {cleanMirrorState} from '../public/boxing-mirror.js';
test('mirror artifacts retain observations and estimated events, never raw frames',()=>{const s=cleanMirrorState({reflection:'I noticed my return',frames:[{private:true}],attempts:[{t:200,type:'JAB',hand:'L',power:99,landmarks:[1]},{t:NaN,type:'HOOK'}]});assert.equal(s.reflection,'I noticed my return');assert.deepEqual(s.attempts,[{t:200,type:'JAB',hand:'L',estimated:true}]);assert.equal('frames' in s,false);});
test('mirror state bounds event history and excludes invalid modes',()=>{const s=cleanMirrorState({sourceMode:'remote-upload',attempts:Array.from({length:100},(_,i)=>({t:i,type:'CROSS',hand:'R'}))});assert.equal(s.sourceMode,null);assert.equal(s.attempts.length,60);assert.equal(s.attempts[0].t,40);});

import {keepMirrorObservation} from '../public/boxing-mirror.js';
const lesson={id:'guard',source:'https://example.com/guard',cues:['Hands up.']};
function ready(){return {lessonId:'guard',sourceMode:'camera',lessonProgress:{guard:{reflection:'My left hand drops.',referenceOpenedAt:'2026-09-10T15:00:00Z',mirrorStartedAt:'2026-09-10T15:01:00Z',reportedTried:true,sessionId:'s1',sourceMode:'camera'}},attempts:[{t:100,type:'JAB',hand:'L',lessonId:'guard',sessionId:'s1'},{t:200,type:'CROSS',hand:'R',lessonId:'other',sessionId:'s2'}]};}
test('opening camera or writing alone is never recorded as tried',()=>{for(const key of ['reportedTried','referenceOpenedAt','mirrorStartedAt','reflection']){const s=ready();s.lessonProgress.guard[key]=false;assert.equal(keepMirrorObservation(s,lesson).observations.length,0);}});
test('kept reflection preserves its lesson, source and matching session estimates',()=>{const before=ready(),kept=keepMirrorObservation(before,lesson,{id:'o1',recordedAt:'now'});assert.equal(before.observations,undefined);assert.equal(kept.observations[0].attempts.length,1);assert.equal(kept.observations[0].source,lesson.source);assert.equal(kept.observations[0].sessionId,'s1');kept.lessonProgress.guard.reflection='A different thought';assert.equal(kept.observations[0].reflection,'My left hand drops.');const second=keepMirrorObservation(kept,lesson,{id:'o2'});second.observations[0].attempts[0].t=999;assert.equal(kept.observations[0].attempts[0].t,100);assert.equal(second.observations.length,2);});
test('JSON restore preserves each lesson draft and immutable observation history',()=>{const s=keepMirrorObservation(ready(),lesson,{id:'o1'});s.lessonProgress.other={reflection:'My feet crossed',reportedTried:false};const restored=cleanMirrorState(JSON.parse(JSON.stringify(s)));assert.equal(restored.lessonProgress.guard.reflection,'My left hand drops.');assert.equal(restored.lessonProgress.other.reflection,'My feet crossed');assert.equal(restored.observations[0].reportedTried,true);assert.equal(restored.observations[0].attempts[0].estimated,true);});
